language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs

services:
 - xvfb

script: 
  # Console test
  - qmake -qt=qt5 BoenkenConsoleTest.pro
  - make --silent debug
  - make clean
  - ./BoenkenConsoleTest
  # Desktop test
  - qmake -qt=qt5 BoenkenDesktopTest.pro
  - make --silent debug
  - make clean
  - ./BoenkenDesktopTest
  # Console
  - qmake -qt=qt5 BoenkenConsole.pro
  - make --silent debug
  - make clean
  - ./BoenkenConsole & 
  # Desktop test
  - qmake -qt=qt5 BoenkenDesktop.pro
  - make --silent debug
  - make clean
  - ./BoenkenDesktop &
  # Code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint

after_success: 
  - bash <(curl -s https://codecov.io/bash)
