language: cpp
dist: xenial
compiler: gcc

addons:
  # Boost
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs


# Xenial
services:
 - xvfb

script: 
  # Console test
  - qmake -qt=qt5 BoenkenConsoleTest.pro
  - make --silent debug
  - make clean
  - ./BoenkenConsoleTest
  # Desktop test
  #- qmake -qt=qt5 BoenkenDesktopTest.pro
  #- make --silent debug
  #- make clean
  #- ./BoenkenDesktopTest
  # Console
  - qmake -qt=qt5 BoenkenConsole.pro
  - make --silent debug
  - make clean
  - ./BoenkenConsole & 
  # Desktop test
  - qmake -qt=qt5 BoenkenDesktop.pro
  - make --silent debug
  - make clean
  - ./BoenkenDesktop &
  # Code coverage
  - ./get_code_cov
  - codecov
  # OCLint
  - ./do_oclint

after_success: 
  - bash <(curl -s https://codecov.io/bash)
