sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5
  - ./install_oclint.sh

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Prerequisites
  - ./download_other_githubs
  # Console test
  - qmake -qt=qt5 BoenkenConsoleTest.pro
  - make debug
  - ./BoenkenConsoleTest
  # Desktop test
  - qmake -qt=qt5 BoenkenDesktopTest.pro
  - make debug
  - ./BoenkenDesktopTest
  # Console
  - qmake -qt=qt5 BoenkenConsole.pro
  - make debug
  - ./BoenkenConsole & 
  # Desktop test
  - qmake -qt=qt5 BoenkenDesktop.pro
  - make debug
  - ./BoenkenDesktop &
  # Code coverage
  - ./get_code_cov.sh
  - codecov
  # OCLint
  - ./do_oclint.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)
