sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  - sudo apt-get update -qq

install: sudo apt-get install -qq g++-5

addons: 
  apt: 
    packages: 
    - libboost-all-dev
    - libwt-dev

script: 
 - ./build.sh

after_success:
  - codecov
