language: cpp
dist: xenial
compiler: gcc

addons:
  # Boost
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  #- sudo apt-get update -qq

install: 
  # C++14
  #- sudo apt install -qq g++-6
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  #- sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  #- export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Wt
  #- sudo apt-get install witty witty-dbg witty-dev witty-doc
  # Codecov
  #- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Others
  - ./download_other_githubs


# Xenial
services:
 - xvfb

# Trusty
# Start virtual X server
# before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script: 
  # Console test
  - qmake -qt=qt5 BoenkenConsoleTest.pro
  - make --silent debug
  - make clean
  - ./BoenkenConsoleTest
  # Desktop test
  #- qmake -qt=qt5 BoenkenDesktopTest.pro
  #- make --silent debug
  #- make clean
  #- ./BoenkenDesktopTest
  # Console
  - qmake -qt=qt5 BoenkenConsole.pro
  - make --silent debug
  - make clean
  - ./BoenkenConsole & 
  # Desktop test
  - qmake -qt=qt5 BoenkenDesktop.pro
  - make --silent debug
  - make clean
  - ./BoenkenDesktop &
  # Code coverage
  - ./get_code_cov
  - codecov
  # OCLint
  - ./do_oclint

after_success: 
  - bash <(curl -s https://codecov.io/bash)
